format_version: 3
pipelines:  
  jr-java-quickstart:
    lock_behavior: lockOnFailure
    group: SimpleWebApp
    materials:
      repo:
        git: https://github.com/JimmyRomero/JR_simple-web-app.git
        branch: practice_Continuous_Testing
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "assemble"                      
              artifacts:
                - build:
                    source: build/libs/*.war
                    destination: war
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments: 
                      - "clean"
                      - "test"
                      - "jacocoTestReport"
                      - "check"
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html
                - build:
                    source: build/reports/jacoco/**/*
                    destination: jacoco
                - build:
                    source: build/reports/checkstyle/*
                    destination: checkstyle
                - build:
                    source: build/reports/findbugs/*
                    destination: findbugs
                - build:
                    source: build/reports/pmd/*
                    destination: pmd
                - test:
                    source: build/test-results/test/*.xml
                    destination: xml                    
              tabs:
                Junit_Test: html/index.html
                Code_Coverage: jacoco/index.html
                checkstyle: checkstyle/main.html
                findbugs: findbugs/main.html
                pmd: pmd/main.html
      - CodeQuality:
          jobs:
            Check:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "sonarqube"
      - Deploy:
          jobs:
            Application:
              tasks:
                - fetch:                    
                    stage: Build
                    job: building
                    source: war/
                - exec:
                    command: ./gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.109.116
                      - -Pwar_path=war
                      - -Pkey_path=/home/go/jindevops.pem
                      - -Pwar_name=JR_simple-web-app
      - Acceptance:
          jobs:
            Acceptance:
              tasks:              
                - exec:
                    command: ./acceptance/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - acceptance
              artifacts:
                - build:
                    source: acceptance/build/reports/cucumber-reports/cucumber-html-reports/*
                    destination: cucumberReport      
              tabs:
                cucumber: cucumberReport/overview-features.html  
